site_name: PySpark Lakehouse - Delta e Iceberg
site_author: Ana Julia, Janaina e Laura

nav:
  - Cenário e Modelagem (ER): index.md
  - Apache Spark: spark.md
  - Delta Lake: delta.md
  - Apache Iceberg: iceberg.md

theme: readthedocs